Algoritmo "problema idades"

Var

    N1,N2: caractere
    I1,I2: inteiro
    M: real

Inicio

    escreval("dados da primeira pessoa")
    escreva("nome:")
    leia(n1)
    escreva("idade:")
    leia(i1)
    escreval("dados da segunda pessoa")
    escreva("nome:")
    leia(n2)
    escreva("idade:")
    leia(i2)
    m <- (i1 + i2) / 2
    escreval("Idade media de ", n1, " e ", n2, " é ", m:4:1, " anos")

Fimalgoritmo